//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemenExchangeApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YemenExchangeApi.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email mustn&apos;t be empty.
        /// </summary>
        public static string email_not_empty {
            get {
                return ResourceManager.GetString("email_not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is not existing in system.
        /// </summary>
        public static string email_not_existing {
            get {
                return ResourceManager.GetString("email_not_existing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invaild email format.
        /// </summary>
        public static string email_wrong_format {
            get {
                return ResourceManager.GetString("email_wrong_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Format.
        /// </summary>
        public static string format_error {
            get {
                return ResourceManager.GetString("format_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identity card image not set in customer profile.
        /// </summary>
        public static string identity_not_found {
            get {
                return ResourceManager.GetString("identity_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identity card image not set.
        /// </summary>
        public static string image_not_set {
            get {
                return ResourceManager.GetString("image_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory field.
        /// </summary>
        public static string mandatory_field {
            get {
                return ResourceManager.GetString("mandatory_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password mustn&apos;t be empty.
        /// </summary>
        public static string password_not_empty {
            get {
                return ResourceManager.GetString("password_not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver name isn&apos;t forth.
        /// </summary>
        public static string receiver__forth_names_error {
            get {
                return ResourceManager.GetString("receiver__forth_names_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender name isn&apos;t forth.
        /// </summary>
        public static string sender_forth_names_error {
            get {
                return ResourceManager.GetString("sender_forth_names_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transformNo is empty.
        /// </summary>
        public static string transform_empty {
            get {
                return ResourceManager.GetString("transform_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransformNo not existing.
        /// </summary>
        public static string transform_not_found {
            get {
                return ResourceManager.GetString("transform_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong data access.
        /// </summary>
        public static string wrong_access {
            get {
                return ResourceManager.GetString("wrong_access", resourceCulture);
            }
        }
    }
}
